Aplikacja/urls.py
from django.conf.urls import url
from django.contrib import admin
from app.views import OrderListView, GetMessageView, MyMessageView, MessageView,  OrderView, CustomerDetailView,  BaseView, UserLoginView, UserLogoutView, NewUserView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restauracja$', BaseView.as_view(), name= 'base'),
    url(r'^login$', UserLoginView.as_view(), name ='login'),
    url(r'^logout$', UserLogoutView.as_view(), name = 'logout'),
    url(r'^new_user$', NewUserView.as_view(), name = 'new'),
    url(r'^customers_detail/(?P<user_id>(\d)+)', CustomerDetailView.as_view(), name = 'detale'),
    url(r'^new_order', OrderView.as_view(), name = 'order'),
    url(r'^message', MessageView.as_view(), name='message'),
    url(r'^my_message', MyMessageView.as_view(), name= 'my_message'),
    url(r'^get_message', GetMessageView.as_view(), name = 'get_message'),
    url(r'^order_list', OrderListView.as_view(), name= 'order_list')
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


# Create your models here.

 
class Customer(AbstractUser):
    birth_date = models.DateField(null=True, blank=True)
    def __str__(self):
        return self.username
    
kind_of_food = (
    (1, 'Przystawki'),
    (2, 'Zupy'),
    (3, 'Dania główne'),
    (4, 'Dodatki'),
    (5, 'Desery'),
    (6, 'Napoje')
)
    
class Food(models.Model):
    name = models.CharField(max_length=256)
    price = models.IntegerField(default=0)
    type = models.IntegerField(choices=kind_of_food, default= 1)
#     customer = models.ManyToManyField(Customer,  blank=True, )

    def __str__(self):
        return self.name+"; CENA:"+str(self.price)
    
class Message(models.Model):
    title = models.CharField(max_length = 125)
    text = models.TextField(max_length=50000)
    creation_date = models.DateTimeField(auto_now_add =True)
    customer = models.ForeignKey(Customer)
    
class Order(models.Model):
    customer = models.ForeignKey(Customer)
    food = models.ForeignKey(Food)
    quantity = models.IntegerField(null = True, blank=True , default= 1)
    creation_date = models.DateTimeField(auto_now_add =True)
#     SELECT sql FROM sqlite_master WHERE tbl_name = 'app_food_customer' AND type = 'table'
    
    
class Bonus(models.Model):  
    customer = models.ForeignKey(Customer)
    text = models.TextField(max_length=50000)
    creation_date = models.DateTimeField(auto_now_add =True)
    

app/templates/all_message.html
{% extends "base.html" %}

{% block content %}
	{% csrf_token %}
	<p> <a href = "{% url 'get_message' %}">Otrzymane wiadomości</a><p>
	<p> <a href = "{% url 'message' %}">Utwórz nową wiadomość</a><p>
	<h3>Wiadomości</h3>
	{% for t in texts %}
		<p> Tytuł: {{ t.title }}</p>
		<p> Treść: {{ t.text }} </p>
		<p> {{ t.creation_date }} </p>
	
		<hr>
	{% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<meta charset="UTF-8">
<title>Wesoła</title>
</head>
<body>
	<p>{{ date }}</p>

	{%if request.user.is_authenticated %}
	    <p> {{ request.user.username }}
	    <a href = "{% url 'logout' %}" >Logout</a></p>
        <div  id='div1'><p><a href = "{% url 'order' %}"><button type='submit'>Pokaż menu</button></a></p>
        <p><a href='/customers_detail/{{ user_id }}'><button type='submit'>Pokaż dane</button></a><br><br><br><br></div>
    {% else %}
        <p><a href = "{% url 'login' %}">Login</a></p>
    {% endif %}
	<div id='div2'><h1>Restauracja "Wesoła"</h1>
	{% block content %}{%endblock%}</div>
	

</body>
</html>

app/templates/customer_detail.html
{% extends "base.html" %}

{% block content %}
	{% csrf_token %}
		<p>Imię: {{ request.user.first_name }} </p>
		<p>Nazwisko : {{ request.user.last_name }} </p>
		<p>Nick: {{request.user.username }} </p>
		<p>Email : {{ request.user.email }} </p>
		
		<p><a href = "{% url 'get_message' %}">Otrzymane wiadomości</a></p>
		<p><a href = "{% url 'message' %}">Wyślij wiadomość do restauracji</a></p>
		
		
{% endblock %}

app/templates/get_message.html
{% extends "base.html" %}

{% block content %}
	{% csrf_token %}
	<p> <a href = "{% url 'get_message' %}">Otrzymane wiadomości</a><p>
	<p> <a href = "{% url 'message' %}">Utwórz nową wiadomość</a><p>
	{% if promocje %} 
	<h3>Twoje promocje</h3>
		{% for p in promocje %}
		<p> {{ p.text }} </p>
		<hr>
		{% endfor %}
	{% endif %}
	
{% endblock %}

app/templates/message.html
{% extends "base.html" %}

{% block content %}
	<p> <a href = "{% url 'my_message' %}">Pokaż moje wiadomości</a><p>
	<form method = 'post'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type= 'submit' value='Wyślij wiadomość' style ='color: salmon'>
	</form>
	
{% endblock %}

app/templates/new_user.html
{% extends "base.html" %}

{% block content %}
	<form method = 'post'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type= 'submit'>
	</form>
	
{% endblock %}

app/templates/order.html
{% extends "base.html" %}
{% block content %}
<form method = 'post'>
	
	{% csrf_token %}
		<p><a href = "{% url 'order_list' %}">Pokaż poprzednie zamówienia</a></p>
		
	    {% for f in Przystawki %}
	  	<hr>
	  	<ul> <h3>{{f.get_type_display }}</h3> </ul>
	  	<hr>
	    	<li> {{ f.name }}  cena: {{ f.price }}  ilość: <input type = 'number' min="0" max="100" name="{{ f.id }}"  value="0"></input></li>
	    
	    {% endfor %}
	   
	    {% for f in Zupy %}
	  	<hr>
	  	<ul> <h3>{{f.get_type_display }}</h3> </ul>
	  	<hr>
	    	<li> {{ f.name }}  cena: {{ f.price }}  ilość: <input type = 'number' maxlenght='2' name="{{ f.id }}"  value="0"></input></li>
	    
	    {% endfor %}
	   
	   
	    {% for f in Dania %}
	  	<hr>
	  	<ul> <h3>{{f.get_type_display }}</h3> </ul>
	  	<hr>
	    	<li> {{ f.name }}  cena: {{ f.price }}  ilość: <input type = 'number' maxlenght='2' name="{{ f.id }}"  value="0"></input></li>
	    
	    {% endfor %}
	   
	   
	    {% for f in Dodatki %}
	  	<hr>
	  	<ul> <h3>{{f.get_type_display }}</h3> </ul>
	  	<hr>
	    	<li> {{ f.name }}  cena: {{ f.price }}  ilość: <input type = 'number' maxlenght='2' name="{{ f.id }}"  value="0"></input></li>
	    
	    {% endfor %}
	   
	   
	   	{% for f in Desery %}
	  	<hr>
	  	<ul> <h3>{{f.get_type_display }}</h3> </ul>
	  	<hr>
	    	<li> {{ f.name }}  cena: {{ f.price }}  ilość: <input type = 'number' maxlenght='2' name="{{ f.id }}"  value="0"></input></li>
	    
	    {% endfor %}
	   
	   	{% for f in Napoje %}
	  	<hr>
	  	<ul> <h3>{{f.get_type_display }}</h3> </ul>
	  	<hr>
	    	<li> {{ f.name }}  cena: {{ f.price }}  ilość: <input type = 'number' maxlenght='2' name="{{ f.id }}"  value="0"></input></li>
	    
	   {% endfor %}
	<p><button type='submit'>Zamów</button></p>
	</form>
{% endblock %}

app/templates/order_list.html
{% extends "base.html" %}

{% block content %}
	{% csrf_token %}
	<p> Lista Twoich zamówień</p>
	<p> Cena ostatniego zamówienia: {{ last_order }} </p>
	<br>
	<p>Ilosc wszystkich zamówionych produktów: {{ quant_orders }}</p>
	<p>Cena wszystkich zamowień: {{ suma }} </p>
	
	
	<hr><hr>
	{% for o in orders %}
		{% if o.quantity != 0 %}
			<p> Produkt: {{ o.food }} </p>
			<p> Ilość: {{ o.quantity }} </p>
			<p> Data zamówienia: {{ o.creation_date }} </p>
			<hr>
		{% endif %}
	{% endfor %}
	
{% endblock %}

app/templates/user_login.html
{% extends "base.html" %}
{% block content %}
	<p> <a href = "{% url 'new' %}">Zarejestruj</a><p>

	<form method = 'post'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type= 'submit'>
	</form>
{% endblock %}